# Generated by Django 6.0.3 on 2026-03-25 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('semester', models.PositiveIntegerField(default=1)),
                ('batch', models.CharField(help_text='e.g., 2023-2027', max_length=20)),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('father_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('guardian_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('category', models.CharField(choices=[('general', 'General'), ('obc', 'OBC'), ('sc', 'SC'), ('st', 'ST'), ('ews', 'EWS')], default='general', max_length=20)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['roll_number'],
            },
        ),
    ]
