# Generated by Django 6.0.3 on 2026-03-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('course_type', models.CharField(choices=[('ug', 'Undergraduate'), ('pg', 'Postgraduate'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], default='ug', max_length=20)),
                ('duration_years', models.PositiveIntegerField(default=4, verbose_name='Duration (Years)')),
                ('total_semesters', models.PositiveIntegerField(default=8)),
                ('description', models.TextField(blank=True, null=True)),
                ('eligibility', models.TextField(blank=True, help_text='Eligibility criteria', null=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester_number', models.PositiveIntegerField()),
                ('start_month', models.PositiveIntegerField(default=1, help_text='Month when semester starts (1-12)')),
                ('end_month', models.PositiveIntegerField(default=6, help_text='Month when semester ends (1-12)')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['course', 'semester_number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('subject_type', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical'), ('lab', 'Laboratory'), ('project', 'Project')], default='theory', max_length=20)),
                ('credits', models.PositiveIntegerField(default=3, help_text='Credit hours for this subject')),
                ('theory_hours', models.PositiveIntegerField(default=3, help_text='Theory hours per week')),
                ('practical_hours', models.PositiveIntegerField(default=0, help_text='Practical hours per week')),
                ('max_marks', models.PositiveIntegerField(default=100, verbose_name='Maximum Marks')),
                ('passing_marks', models.PositiveIntegerField(default=40, verbose_name='Passing Marks')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['semester', 'code'],
            },
        ),
    ]
