# Generated by Django 6.0.3 on 2026-03-25 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('block_type', models.CharField(choices=[('boys', 'Boys Hostel'), ('girls', 'Girls Hostel')], max_length=10)),
                ('total_rooms', models.PositiveIntegerField(default=0)),
                ('total_capacity', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('warden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_blocks', to='faculty.faculty')),
            ],
            options={
                'verbose_name': 'Hostel Block',
                'verbose_name_plural': 'Hostel Blocks',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('room_number', models.CharField(max_length=20)),
                ('floor', models.PositiveIntegerField()),
                ('room_type', models.CharField(choices=[('single', 'Single Occupancy'), ('double', 'Double Occupancy'), ('triple', 'Triple Occupancy'), ('dormitory', 'Dormitory')], default='double', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('current_occupancy', models.PositiveIntegerField(default=0)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('hostel_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostelblock')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['hostel_block', 'room_number'],
                'unique_together': {('hostel_block', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='RoomAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allotment_date', models.DateField()),
                ('vacated_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('vacated', 'Vacated'), ('transferred', 'Transferred')], default='active', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='hostel.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_allotments', to='students.student')),
            ],
            options={
                'verbose_name': 'Room Allotment',
                'verbose_name_plural': 'Room Allotments',
                'ordering': ['-allotment_date'],
            },
        ),
    ]
