# Generated by Django 6.0.3 on 2026-03-25 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('designation', models.CharField(choices=[('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('lecturer', 'Lecturer'), ('senior_lecturer', 'Senior Lecturer'), ('lab_assistant', 'Lab Assistant'), ('hod', 'Head of Department')], default='lecturer', max_length=30)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('visiting', 'Visiting'), ('contract', 'Contract')], default='full_time', max_length=20)),
                ('joining_date', models.DateField()),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Experience (Years)')),
                ('qualification', models.CharField(help_text='e.g., Ph.D, M.Tech, M.Sc', max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=200, null=True)),
                ('publications', models.PositiveIntegerField(default=0, verbose_name='Research Publications')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('research_interests', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_members', to='academics.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculty Members',
                'ordering': ['employee_id'],
            },
        ),
    ]
